#!/usr/bin/env python3
"""
Adds translations for the redesigned UIKit UI strings (tab bar, Home, recipe
detail, Favorites/Discover/Settings shell) to every build localization.

Keys are the English source strings themselves (matching the project's existing
`"Ingredients" = "Ingredients";` convention), so the Swift side just calls
`"Start cooking".localized`. Already-present keys are left untouched, so this
script is safe to re-run.
"""

import os

LDIR = os.path.join(os.path.dirname(__file__), "..",
                    "WhichFood", "Utils", "Locale", "Languages")

# Regional variants reuse their base language's copy.
BASE = {
    "en-GB": "en", "en-AU": "en",
    "es-US": "es", "es-419": "es",
    "fr-CA": "fr", "pt-PT": "pt",
}

# lang order for readability only
# english_source : { lang_code : translation }
T = {
    # ---- Tab bar ----
    "Home": {"tr":"Ana Sayfa","de":"Start","es":"Inicio","fr":"Accueil","it":"Home","pt":"Início","nl":"Home","ru":"Главная","ja":"ホーム","ko":"홈","zh-Hans":"主页","ar":"الرئيسية","cs":"Domů","fi":"Koti","hr":"Početna","fa":"خانه"},
    "Favorites": {"tr":"Favoriler","de":"Favoriten","es":"Favoritos","fr":"Favoris","it":"Preferiti","pt":"Favoritos","nl":"Favorieten","ru":"Избранное","ja":"お気に入り","ko":"즐겨찾기","zh-Hans":"收藏","ar":"المفضلة","cs":"Oblíbené","fi":"Suosikit","hr":"Favoriti","fa":"علاقه‌مندی‌ها"},
    "Search": {"tr":"Ara","de":"Suche","es":"Buscar","fr":"Recherche","it":"Cerca","pt":"Buscar","nl":"Zoeken","ru":"Поиск","ja":"検索","ko":"검색","zh-Hans":"搜索","ar":"بحث","cs":"Hledat","fi":"Haku","hr":"Pretraga","fa":"جستجو"},
    "Settings": {"tr":"Ayarlar","de":"Einstellungen","es":"Ajustes","fr":"Réglages","it":"Impostazioni","pt":"Definições","nl":"Instellingen","ru":"Настройки","ja":"設定","ko":"설정","zh-Hans":"设置","ar":"الإعدادات","cs":"Nastavení","fi":"Asetukset","hr":"Postavke","fa":"تنظیمات"},

    # ---- Generic ----
    "OK": {"tr":"Tamam","de":"OK","es":"Aceptar","fr":"OK","it":"OK","pt":"OK","nl":"OK","ru":"ОК","ja":"OK","ko":"확인","zh-Hans":"确定","ar":"موافق","cs":"OK","fi":"OK","hr":"U redu","fa":"باشه"},
    "Cancel": {"tr":"İptal","de":"Abbrechen","es":"Cancelar","fr":"Annuler","it":"Annulla","pt":"Cancelar","nl":"Annuleren","ru":"Отмена","ja":"キャンセル","ko":"취소","zh-Hans":"取消","ar":"إلغاء","cs":"Zrušit","fi":"Peruuta","hr":"Odustani","fa":"لغو"},
    "Delete": {"tr":"Sil","de":"Löschen","es":"Eliminar","fr":"Supprimer","it":"Elimina","pt":"Apagar","nl":"Verwijderen","ru":"Удалить","ja":"削除","ko":"삭제","zh-Hans":"删除","ar":"حذف","cs":"Smazat","fi":"Poista","hr":"Izbriši","fa":"حذف"},
    "Something went wrong": {"tr":"Bir şeyler ters gitti","de":"Etwas ist schiefgelaufen","es":"Algo salió mal","fr":"Une erreur est survenue","it":"Qualcosa è andato storto","pt":"Algo correu mal","nl":"Er ging iets mis","ru":"Что-то пошло не так","ja":"問題が発生しました","ko":"문제가 발생했습니다","zh-Hans":"出错了","ar":"حدث خطأ ما","cs":"Něco se pokazilo","fi":"Jokin meni pieleen","hr":"Nešto je pošlo po zlu","fa":"مشکلی پیش آمد"},

    # ---- Photo source sheet ----
    "Add a photo": {"tr":"Fotoğraf ekle","de":"Foto hinzufügen","es":"Añadir una foto","fr":"Ajouter une photo","it":"Aggiungi una foto","pt":"Adicionar uma foto","nl":"Foto toevoegen","ru":"Добавить фото","ja":"写真を追加","ko":"사진 추가","zh-Hans":"添加照片","ar":"إضافة صورة","cs":"Přidat fotku","fi":"Lisää kuva","hr":"Dodaj fotografiju","fa":"افزودن عکس"},
    "Snap a dish or pick one from your library.": {"tr":"Bir yemeğin fotoğrafını çek ya da galerinden seç.","de":"Fotografiere ein Gericht oder wähle eines aus deiner Mediathek.","es":"Haz una foto de un plato o elige una de tu galería.","fr":"Photographiez un plat ou choisissez-en un dans votre galerie.","it":"Fotografa un piatto o scegline uno dalla galleria.","pt":"Tira uma foto de um prato ou escolhe uma da galeria.","nl":"Maak een foto van een gerecht of kies er een uit je bibliotheek.","ru":"Сфотографируйте блюдо или выберите фото из галереи.","ja":"料理を撮影するか、ライブラリから選んでください。","ko":"요리를 촬영하거나 라이브러리에서 선택하세요.","zh-Hans":"拍一张菜品照片，或从相册中选择。","ar":"التقط صورة لطبق أو اختر واحدة من مكتبتك.","cs":"Vyfoťte jídlo nebo vyberte fotku z knihovny.","fi":"Ota kuva ruoasta tai valitse kuva kirjastosta.","hr":"Slikaj jelo ili odaberi fotografiju iz galerije.","fa":"از یک غذا عکس بگیرید یا از گالری انتخاب کنید."},
    "Take a photo": {"tr":"Fotoğraf çek","de":"Foto aufnehmen","es":"Hacer una foto","fr":"Prendre une photo","it":"Scatta una foto","pt":"Tirar uma foto","nl":"Foto maken","ru":"Сделать фото","ja":"写真を撮る","ko":"사진 촬영","zh-Hans":"拍照","ar":"التقاط صورة","cs":"Vyfotit","fi":"Ota kuva","hr":"Snimi fotografiju","fa":"گرفتن عکس"},
    "Use the camera": {"tr":"Kamerayı kullan","de":"Kamera verwenden","es":"Usar la cámara","fr":"Utiliser l’appareil photo","it":"Usa la fotocamera","pt":"Usar a câmara","nl":"Camera gebruiken","ru":"Использовать камеру","ja":"カメラを使う","ko":"카메라 사용","zh-Hans":"使用相机","ar":"استخدام الكاميرا","cs":"Použít fotoaparát","fi":"Käytä kameraa","hr":"Koristi kameru","fa":"استفاده از دوربین"},
    "Choose from library": {"tr":"Galeriden seç","de":"Aus Mediathek wählen","es":"Elegir de la galería","fr":"Choisir dans la galerie","it":"Scegli dalla galleria","pt":"Escolher da galeria","nl":"Kies uit bibliotheek","ru":"Выбрать из галереи","ja":"ライブラリから選択","ko":"라이브러리에서 선택","zh-Hans":"从相册选择","ar":"اختيار من المكتبة","cs":"Vybrat z knihovny","fi":"Valitse kirjastosta","hr":"Odaberi iz galerije","fa":"انتخاب از گالری"},
    "Pick an existing photo": {"tr":"Mevcut bir fotoğraf seç","de":"Vorhandenes Foto wählen","es":"Elegir una foto existente","fr":"Choisir une photo existante","it":"Scegli una foto esistente","pt":"Escolher uma foto existente","nl":"Kies een bestaande foto","ru":"Выбрать существующее фото","ja":"既存の写真を選ぶ","ko":"기존 사진 선택","zh-Hans":"选择已有照片","ar":"اختيار صورة موجودة","cs":"Vybrat existující fotku","fi":"Valitse olemassa oleva kuva","hr":"Odaberi postojeću fotografiju","fa":"انتخاب یک عکس موجود"},
    "Recipe from a photo": {"tr":"Fotoğraftan tarif","de":"Rezept aus einem Foto","es":"Receta a partir de una foto","fr":"Recette à partir d’une photo","it":"Ricetta da una foto","pt":"Receita a partir de uma foto","nl":"Recept van een foto","ru":"Рецепт по фото","ja":"写真からレシピ","ko":"사진으로 레시피","zh-Hans":"从照片生成食谱","ar":"وصفة من صورة","cs":"Recept z fotky","fi":"Resepti kuvasta","hr":"Recept iz fotografije","fa":"دستور از روی عکس"},

    # ---- Recipe detail ----
    "Save to my recipes": {"tr":"Tariflerime kaydet","de":"Zu meinen Rezepten hinzufügen","es":"Guardar en mis recetas","fr":"Enregistrer dans mes recettes","it":"Salva nelle mie ricette","pt":"Guardar nas minhas receitas","nl":"Opslaan in mijn recepten","ru":"Сохранить в мои рецепты","ja":"マイレシピに保存","ko":"내 레시피에 저장","zh-Hans":"保存到我的食谱","ar":"حفظ في وصفاتي","cs":"Uložit do mých receptů","fi":"Tallenna resepteihini","hr":"Spremi u moje recepte","fa":"ذخیره در دستورهای من"},
    "PREP": {"tr":"HAZIRLIK","de":"VORBER.","es":"PREP.","fr":"PRÉP.","it":"PREP.","pt":"PREP.","nl":"VOORBER.","ru":"ПОДГОТ.","ja":"準備","ko":"준비","zh-Hans":"准备","ar":"التحضير","cs":"PŘÍPRAVA","fi":"VALM.","hr":"PRIPREMA","fa":"آماده‌سازی"},
    "COOK": {"tr":"PİŞİRME","de":"KOCHEN","es":"COCCIÓN","fr":"CUISSON","it":"COTTURA","pt":"COZEDURA","nl":"KOKEN","ru":"ГОТОВКА","ja":"調理","ko":"조리","zh-Hans":"烹饪","ar":"الطهي","cs":"VAŘENÍ","fi":"KYPS.","hr":"KUHANJE","fa":"پخت"},
    "SERVES": {"tr":"KİŞİLİK","de":"PORTIONEN","es":"RACIONES","fr":"PORTIONS","it":"PORZIONI","pt":"DOSES","nl":"PORTIES","ru":"ПОРЦИИ","ja":"人前","ko":"인분","zh-Hans":"份量","ar":"يكفي لـ","cs":"PORCE","fi":"ANNOKSET","hr":"OSOBA","fa":"برای"},
    "LEVEL": {"tr":"SEVİYE","de":"NIVEAU","es":"NIVEL","fr":"NIVEAU","it":"LIVELLO","pt":"NÍVEL","nl":"NIVEAU","ru":"УРОВЕНЬ","ja":"レベル","ko":"난이도","zh-Hans":"难度","ar":"المستوى","cs":"ÚROVEŇ","fi":"TASO","hr":"RAZINA","fa":"سطح"},
    "Easy": {"tr":"Kolay","de":"Einfach","es":"Fácil","fr":"Facile","it":"Facile","pt":"Fácil","nl":"Makkelijk","ru":"Легко","ja":"かんたん","ko":"쉬움","zh-Hans":"简单","ar":"سهل","cs":"Snadné","fi":"Helppo","hr":"Lako","fa":"آسان"},
    "Start cooking": {"tr":"Pişirmeye başla","de":"Loskochen","es":"Empezar a cocinar","fr":"Commencer à cuisiner","it":"Inizia a cucinare","pt":"Começar a cozinhar","nl":"Begin met koken","ru":"Начать готовить","ja":"調理を始める","ko":"요리 시작","zh-Hans":"开始烹饪","ar":"ابدأ الطهي","cs":"Začít vařit","fi":"Aloita kokkaus","hr":"Počni kuhati","fa":"شروع پخت"},
    "Remix": {"tr":"Yeniden yorumla","de":"Remix","es":"Remezclar","fr":"Remixer","it":"Rielabora","pt":"Remisturar","nl":"Remix","ru":"Переделать","ja":"アレンジ","ko":"변형","zh-Hans":"改造","ar":"إعادة مزج","cs":"Remix","fi":"Muokkaa","hr":"Remiks","fa":"بازآفرینی"},
    "Pick a twist": {"tr":"Bir varyasyon seç","de":"Wähle eine Variante","es":"Elige una variación","fr":"Choisissez une variante","it":"Scegli una variante","pt":"Escolhe uma variação","nl":"Kies een variatie","ru":"Выберите вариацию","ja":"アレンジを選ぶ","ko":"변형 선택","zh-Hans":"选择一个变化","ar":"اختر تعديلاً","cs":"Vyberte variaci","fi":"Valitse muunnos","hr":"Odaberi varijaciju","fa":"یک تغییر انتخاب کنید"},
    "Make it healthier": {"tr":"Daha sağlıklı yap","de":"Gesünder machen","es":"Hacerla más saludable","fr":"La rendre plus saine","it":"Rendila più sana","pt":"Torná-la mais saudável","nl":"Gezonder maken","ru":"Сделать полезнее","ja":"よりヘルシーに","ko":"더 건강하게","zh-Hans":"更健康","ar":"اجعلها أكثر صحة","cs":"Udělat zdravější","fi":"Tee terveellisemmäksi","hr":"Učini zdravijim","fa":"سالم‌ترش کن"},
    "Make it spicier": {"tr":"Daha acılı yap","de":"Schärfer machen","es":"Hacerla más picante","fr":"La rendre plus épicée","it":"Rendila più piccante","pt":"Torná-la mais picante","nl":"Pittiger maken","ru":"Сделать острее","ja":"より辛く","ko":"더 맵게","zh-Hans":"更辣","ar":"اجعلها أكثر حرارة","cs":"Udělat pikantnější","fi":"Tee tulisemmaksi","hr":"Učini ljućim","fa":"تندترش کن"},
    "Make it vegetarian": {"tr":"Vejetaryen yap","de":"Vegetarisch machen","es":"Hacerla vegetariana","fr":"La rendre végétarienne","it":"Rendila vegetariana","pt":"Torná-la vegetariana","nl":"Vegetarisch maken","ru":"Сделать вегетарианским","ja":"ベジタリアンに","ko":"채식으로","zh-Hans":"改成素食","ar":"اجعلها نباتية","cs":"Udělat vegetariánské","fi":"Tee kasvisruoaksi","hr":"Učini vegetarijanskim","fa":"گیاهی‌اش کن"},
    "Make it quicker": {"tr":"Daha hızlı yap","de":"Schneller machen","es":"Hacerla más rápida","fr":"La rendre plus rapide","it":"Rendila più veloce","pt":"Torná-la mais rápida","nl":"Sneller maken","ru":"Сделать быстрее","ja":"より手早く","ko":"더 빠르게","zh-Hans":"更快捷","ar":"اجعلها أسرع","cs":"Udělat rychlejší","fi":"Tee nopeammaksi","hr":"Učini bržim","fa":"سریع‌ترش کن"},
    "Remixing…": {"tr":"Yeniden yorumlanıyor…","de":"Wird neu gemischt…","es":"Remezclando…","fr":"Remixage…","it":"Rielaborazione…","pt":"A remisturar…","nl":"Remixen…","ru":"Переделываем…","ja":"アレンジ中…","ko":"변형 중…","zh-Hans":"改造中…","ar":"جارٍ إعادة المزج…","cs":"Míchání…","fi":"Muokataan…","hr":"Remiksiranje…","fa":"در حال بازآفرینی…"},

    # ---- Home filter chips (display only; logic keeps English) ----
    "All": {"tr":"Tümü","de":"Alle","es":"Todas","fr":"Tout","it":"Tutte","pt":"Todas","nl":"Alle","ru":"Все","ja":"すべて","ko":"전체","zh-Hans":"全部","ar":"الكل","cs":"Vše","fi":"Kaikki","hr":"Sve","fa":"همه"},
    "Meaty": {"tr":"Etli","de":"Fleisch","es":"Con carne","fr":"Viande","it":"Con carne","pt":"Com carne","nl":"Vlees","ru":"Мясные","ja":"肉料理","ko":"고기","zh-Hans":"肉类","ar":"باللحم","cs":"Masité","fi":"Liharuoat","hr":"Mesno","fa":"گوشتی"},
    "Vegetarian": {"tr":"Vejetaryen","de":"Vegetarisch","es":"Vegetariana","fr":"Végétarien","it":"Vegetariana","pt":"Vegetariana","nl":"Vegetarisch","ru":"Вегетарианские","ja":"ベジタリアン","ko":"채식","zh-Hans":"素食","ar":"نباتي","cs":"Vegetariánské","fi":"Kasvis","hr":"Vegetarijansko","fa":"گیاهی"},
    "Dessert": {"tr":"Tatlı","de":"Dessert","es":"Postre","fr":"Dessert","it":"Dolce","pt":"Sobremesa","nl":"Dessert","ru":"Десерты","ja":"デザート","ko":"디저트","zh-Hans":"甜点","ar":"حلوى","cs":"Dezert","fi":"Jälkiruoat","hr":"Desert","fa":"دسر"},

    # ---- Home ----
    "Let's cook something great.": {"tr":"Hadi harika bir şey pişirelim.","de":"Lass uns etwas Tolles kochen.","es":"Cocinemos algo genial.","fr":"Cuisinons quelque chose de délicieux.","it":"Cuciniamo qualcosa di buono.","pt":"Vamos cozinhar algo delicioso.","nl":"Laten we iets lekkers koken.","ru":"Приготовим что-нибудь вкусное.","ja":"何か美味しいものを作りましょう。","ko":"맛있는 걸 만들어 볼까요.","zh-Hans":"来做点好吃的吧。","ar":"لنطبخ شيئًا رائعًا.","cs":"Uvařme něco skvělého.","fi":"Laitetaan jotain hyvää.","hr":"Skuhajmo nešto sjajno.","fa":"بیایید چیزی عالی بپزیم."},
    "Good morning": {"tr":"Günaydın","de":"Guten Morgen","es":"Buenos días","fr":"Bonjour","it":"Buongiorno","pt":"Bom dia","nl":"Goedemorgen","ru":"Доброе утро","ja":"おはようございます","ko":"좋은 아침이에요","zh-Hans":"早上好","ar":"صباح الخير","cs":"Dobré ráno","fi":"Hyvää huomenta","hr":"Dobro jutro","fa":"صبح بخیر"},
    "Good afternoon": {"tr":"İyi günler","de":"Guten Tag","es":"Buenas tardes","fr":"Bon après-midi","it":"Buon pomeriggio","pt":"Boa tarde","nl":"Goedemiddag","ru":"Добрый день","ja":"こんにちは","ko":"좋은 오후예요","zh-Hans":"下午好","ar":"مساء الخير","cs":"Dobré odpoledne","fi":"Hyvää iltapäivää","hr":"Dobar dan","fa":"ظهر بخیر"},
    "Good evening": {"tr":"İyi akşamlar","de":"Guten Abend","es":"Buenas noches","fr":"Bonsoir","it":"Buonasera","pt":"Boa noite","nl":"Goedenavond","ru":"Добрый вечер","ja":"こんばんは","ko":"좋은 저녁이에요","zh-Hans":"晚上好","ar":"مساء الخير","cs":"Dobrý večer","fi":"Hyvää iltaa","hr":"Dobra večer","fa":"عصر بخیر"},
    "Your recipes": {"tr":"Tariflerin","de":"Deine Rezepte","es":"Tus recetas","fr":"Tes recettes","it":"Le tue ricette","pt":"As tuas receitas","nl":"Jouw recepten","ru":"Ваши рецепты","ja":"あなたのレシピ","ko":"내 레시피","zh-Hans":"你的食谱","ar":"وصفاتك","cs":"Vaše recepty","fi":"Reseptisi","hr":"Vaši recepti","fa":"دستورهای شما"},
    "%d saved": {"tr":"%d kayıtlı","de":"%d gespeichert","es":"%d guardadas","fr":"%d enregistrées","it":"%d salvate","pt":"%d guardadas","nl":"%d opgeslagen","ru":"%d сохранено","ja":"%d件保存","ko":"%d개 저장됨","zh-Hans":"已保存 %d","ar":"%d محفوظة","cs":"%d uloženo","fi":"%d tallennettu","hr":"%d spremljeno","fa":"%d ذخیره‌شده"},
    "From Ingredients": {"tr":"Malzemelerden","de":"Aus Zutaten","es":"Con ingredientes","fr":"À partir d’ingrédients","it":"Dagli ingredienti","pt":"A partir de ingredientes","nl":"Van ingrediënten","ru":"Из ингредиентов","ja":"材料から","ko":"재료로","zh-Hans":"用食材","ar":"من المكوّنات","cs":"Ze surovin","fi":"Aineksista","hr":"Iz sastojaka","fa":"از مواد اولیه"},
    "Use what you already have": {"tr":"Elindekileri kullan","de":"Nutze, was du schon hast","es":"Usa lo que ya tienes","fr":"Utilise ce que tu as déjà","it":"Usa ciò che hai già","pt":"Usa o que já tens","nl":"Gebruik wat je al hebt","ru":"Используйте то, что есть","ja":"あるものを使おう","ko":"가진 재료로 만들기","zh-Hans":"用你手边的食材","ar":"استخدم ما لديك","cs":"Využij, co máš doma","fi":"Käytä mitä sinulla on","hr":"Iskoristi što već imaš","fa":"از آنچه داری استفاده کن"},
    "From Photo": {"tr":"Fotoğraftan","de":"Aus Foto","es":"Con una foto","fr":"À partir d’une photo","it":"Da una foto","pt":"A partir de uma foto","nl":"Van een foto","ru":"По фото","ja":"写真から","ko":"사진으로","zh-Hans":"用照片","ar":"من صورة","cs":"Z fotky","fi":"Kuvasta","hr":"Iz fotografije","fa":"از روی عکس"},
    "Snap a dish, get the recipe": {"tr":"Yemeği çek, tarifi al","de":"Gericht fotografieren, Rezept erhalten","es":"Fotografía un plato y obtén la receta","fr":"Photographie un plat, obtiens la recette","it":"Fotografa un piatto, ottieni la ricetta","pt":"Fotografa um prato e recebe a receita","nl":"Fotografeer een gerecht, krijg het recept","ru":"Сфотографируйте блюдо — получите рецепт","ja":"料理を撮ってレシピを取得","ko":"요리를 찍으면 레시피가","zh-Hans":"拍下菜品，获取食谱","ar":"صوّر الطبق واحصل على الوصفة","cs":"Vyfoť jídlo, získej recept","fi":"Kuvaa annos, saat reseptin","hr":"Slikaj jelo, dobij recept","fa":"از غذا عکس بگیر، دستور بگیر"},
    "Describe a dish… e.g. spicy lentil soup": {"tr":"Bir yemek tarif et… örn. acılı mercimek çorbası","de":"Beschreibe ein Gericht… z. B. scharfe Linsensuppe","es":"Describe un plato… p. ej. sopa de lentejas picante","fr":"Décris un plat… ex. soupe de lentilles épicée","it":"Descrivi un piatto… es. zuppa di lenticchie piccante","pt":"Descreve um prato… ex. sopa de lentilhas picante","nl":"Beschrijf een gerecht… bijv. pittige linzensoep","ru":"Опишите блюдо… напр. острый чечевичный суп","ja":"料理を説明…例：スパイシーなレンズ豆スープ","ko":"요리를 설명하세요… 예: 매운 렌틸 수프","zh-Hans":"描述一道菜…例如香辣扁豆汤","ar":"صف طبقًا… مثل شوربة العدس الحارة","cs":"Popiš jídlo… např. pikantní čočková polévka","fi":"Kuvaile ruokaa… esim. tulinen linssikeitto","hr":"Opiši jelo… npr. ljuta juha od leće","fa":"یک غذا را توصیف کن… مثلاً سوپ عدس تند"},
    "Your cookbook is empty": {"tr":"Yemek kitabın boş","de":"Dein Kochbuch ist leer","es":"Tu recetario está vacío","fr":"Ton livre de recettes est vide","it":"Il tuo ricettario è vuoto","pt":"O teu livro de receitas está vazio","nl":"Je kookboek is leeg","ru":"Ваша книга рецептов пуста","ja":"レシピブックは空です","ko":"요리책이 비어 있어요","zh-Hans":"你的食谱本是空的","ar":"كتاب وصفاتك فارغ","cs":"Vaše kuchařka je prázdná","fi":"Reseptikirjasi on tyhjä","hr":"Vaša kuharica je prazna","fa":"کتاب آشپزی شما خالی است"},
    "No %@ recipes yet": {"tr":"Henüz %@ tarif yok","de":"Noch keine %@-Rezepte","es":"Aún no hay recetas %@","fr":"Pas encore de recettes %@","it":"Ancora nessuna ricetta %@","pt":"Ainda sem receitas %@","nl":"Nog geen %@-recepten","ru":"Пока нет рецептов «%@»","ja":"%@のレシピはまだありません","ko":"아직 %@ 레시피가 없어요","zh-Hans":"暂无%@食谱","ar":"لا توجد وصفات %@ بعد","cs":"Zatím žádné recepty %@","fi":"Ei vielä %@-reseptejä","hr":"Još nema %@ recepata","fa":"هنوز دستور %@ وجود ندارد"},

    # ---- Favorites / Discover ----
    "No favorites yet": {"tr":"Henüz favori yok","de":"Noch keine Favoriten","es":"Aún no hay favoritos","fr":"Pas encore de favoris","it":"Ancora nessun preferito","pt":"Ainda sem favoritos","nl":"Nog geen favorieten","ru":"Пока нет избранного","ja":"お気に入りはまだありません","ko":"아직 즐겨찾기가 없어요","zh-Hans":"还没有收藏","ar":"لا مفضلات بعد","cs":"Zatím žádné oblíbené","fi":"Ei vielä suosikkeja","hr":"Još nema favorita","fa":"هنوز علاقه‌مندی‌ای نیست"},
    "Tap the heart on any recipe to keep it close at hand.": {"tr":"Bir tarifi elinin altında tutmak için kalbe dokun.","de":"Tippe bei einem Rezept auf das Herz, um es griffbereit zu haben.","es":"Toca el corazón de una receta para tenerla a mano.","fr":"Touche le cœur d’une recette pour la garder à portée de main.","it":"Tocca il cuore di una ricetta per averla sempre a portata.","pt":"Toca no coração de uma receita para a teres à mão.","nl":"Tik op het hartje van een recept om het bij de hand te houden.","ru":"Нажмите на сердечко у рецепта, чтобы он был под рукой.","ja":"レシピのハートをタップして手元に保存しましょう。","ko":"레시피의 하트를 눌러 가까이 보관하세요.","zh-Hans":"点按任意食谱上的爱心即可随手收藏。","ar":"اضغط على القلب في أي وصفة لتبقى في متناولك.","cs":"Klepnutím na srdíčko u receptu ho máte po ruce.","fi":"Napauta reseptin sydäntä pitääksesi sen käsillä.","hr":"Dodirni srce na receptu da ti bude pri ruci.","fa":"روی قلب هر دستور بزنید تا در دسترس بماند."},
    "Discover": {"tr":"Keşfet","de":"Entdecken","es":"Descubrir","fr":"Découvrir","it":"Scopri","pt":"Descobrir","nl":"Ontdekken","ru":"Обзор","ja":"見つける","ko":"둘러보기","zh-Hans":"发现","ar":"اكتشف","cs":"Objevujte","fi":"Löydä","hr":"Otkrij","fa":"کشف"},
    "Search recipes…": {"tr":"Tarif ara…","de":"Rezepte suchen…","es":"Buscar recetas…","fr":"Rechercher des recettes…","it":"Cerca ricette…","pt":"Procurar receitas…","nl":"Recepten zoeken…","ru":"Поиск рецептов…","ja":"レシピを検索…","ko":"레시피 검색…","zh-Hans":"搜索食谱…","ar":"ابحث عن وصفات…","cs":"Hledat recepty…","fi":"Hae reseptejä…","hr":"Pretraži recepte…","fa":"جستجوی دستورها…"},
    "Nothing found": {"tr":"Sonuç bulunamadı","de":"Nichts gefunden","es":"No se encontró nada","fr":"Aucun résultat","it":"Nessun risultato","pt":"Nada encontrado","nl":"Niets gevonden","ru":"Ничего не найдено","ja":"何も見つかりません","ko":"결과가 없어요","zh-Hans":"未找到结果","ar":"لا توجد نتائج","cs":"Nic nenalezeno","fi":"Ei tuloksia","hr":"Ništa nije pronađeno","fa":"چیزی پیدا نشد"},
    "From around the web": {"tr":"İnternetten","de":"Aus dem Web","es":"De la web","fr":"Depuis le web","it":"Dal web","pt":"Da web","nl":"Van het web","ru":"Со всего интернета","ja":"ウェブから","ko":"웹에서","zh-Hans":"来自网络","ar":"من الويب","cs":"Z webu","fi":"Verkosta","hr":"S weba","fa":"از سراسر وب"},
    "Your kitchen": {"tr":"Mutfağın","de":"Deine Küche","es":"Tu cocina","fr":"Ta cuisine","it":"La tua cucina","pt":"A tua cozinha","nl":"Jouw keuken","ru":"Ваша кухня","ja":"あなたのキッチン","ko":"내 주방","zh-Hans":"你的厨房","ar":"مطبخك","cs":"Vaše kuchyně","fi":"Keittiösi","hr":"Vaša kuhinja","fa":"آشپزخانه شما"},

    # ---- Discover ----
    "Search recipes": {"tr":"Tarif ara","de":"Rezepte suchen","es":"Buscar recetas","fr":"Rechercher des recettes","it":"Cerca ricette","pt":"Procurar receitas","nl":"Recepten zoeken","ru":"Поиск рецептов","ja":"レシピを検索","ko":"레시피 검색","zh-Hans":"搜索食谱","ar":"ابحث عن وصفات","cs":"Hledat recepty","fi":"Hae reseptejä","hr":"Pretraži recepte","fa":"جستجوی دستورها"},
    "Try a different keyword — or create it from your ingredients instead.": {"tr":"Farklı bir kelime dene — ya da malzemelerinden oluştur.","de":"Versuche ein anderes Stichwort – oder erstelle es aus deinen Zutaten.","es":"Prueba otra palabra clave, o créala con tus ingredientes.","fr":"Essaie un autre mot-clé — ou crée-la à partir de tes ingrédients.","it":"Prova un'altra parola chiave — o creala dai tuoi ingredienti.","pt":"Tenta outra palavra-chave — ou cria-a a partir dos teus ingredientes.","nl":"Probeer een ander trefwoord — of maak het van je ingrediënten.","ru":"Попробуйте другое слово — или создайте рецепт из своих ингредиентов.","ja":"別のキーワードを試すか、手持ちの材料から作りましょう。","ko":"다른 키워드를 시도하거나 가진 재료로 만들어 보세요.","zh-Hans":"换个关键词，或用你的食材来创建。","ar":"جرّب كلمة مختلفة — أو أنشئها من مكوّناتك.","cs":"Zkuste jiné klíčové slovo — nebo ho vytvořte ze surovin.","fi":"Kokeile toista hakusanaa — tai luo se aineksistasi.","hr":"Pokušaj s drugom ključnom riječi — ili je stvori iz svojih sastojaka.","fa":"کلمه دیگری امتحان کن — یا از مواد اولیه‌ات بساز."},

    # ---- Home empty-state messages ----
    "Create a recipe from your ingredients or a food photo to get started.": {"tr":"Başlamak için malzemelerinden ya da bir yemek fotoğrafından tarif oluştur.","de":"Erstelle zum Start ein Rezept aus deinen Zutaten oder einem Foto.","es":"Para empezar, crea una receta con tus ingredientes o una foto.","fr":"Pour commencer, crée une recette à partir de tes ingrédients ou d'une photo.","it":"Per iniziare, crea una ricetta dai tuoi ingredienti o da una foto.","pt":"Para começar, cria uma receita com os teus ingredientes ou uma foto.","nl":"Maak om te beginnen een recept van je ingrediënten of een foto.","ru":"Чтобы начать, создайте рецепт из ингредиентов или по фото.","ja":"まずは材料や写真からレシピを作りましょう。","ko":"시작하려면 재료나 음식 사진으로 레시피를 만들어 보세요.","zh-Hans":"用你的食材或一张美食照片来创建第一份食谱吧。","ar":"للبدء، أنشئ وصفة من مكوّناتك أو من صورة طعام.","cs":"Začněte vytvořením receptu ze surovin nebo z fotky jídla.","fi":"Aloita luomalla resepti aineksistasi tai ruokakuvasta.","hr":"Za početak stvori recept iz sastojaka ili fotografije jela.","fa":"برای شروع، از مواد اولیه یا عکس غذا یک دستور بساز."},
    "Try another filter or create something new.": {"tr":"Başka bir filtre dene ya da yeni bir şey oluştur.","de":"Probiere einen anderen Filter oder erstelle etwas Neues.","es":"Prueba otro filtro o crea algo nuevo.","fr":"Essaie un autre filtre ou crée quelque chose de nouveau.","it":"Prova un altro filtro o crea qualcosa di nuovo.","pt":"Experimenta outro filtro ou cria algo novo.","nl":"Probeer een ander filter of maak iets nieuws.","ru":"Попробуйте другой фильтр или создайте что-то новое.","ja":"別のフィルターを試すか、新しく作りましょう。","ko":"다른 필터를 시도하거나 새로 만들어 보세요.","zh-Hans":"试试其他筛选，或创建新的食谱。","ar":"جرّب فلترًا آخر أو أنشئ شيئًا جديدًا.","cs":"Zkuste jiný filtr nebo vytvořte něco nového.","fi":"Kokeile toista suodatinta tai luo jotain uutta.","hr":"Pokušaj s drugim filtrom ili stvori nešto novo.","fa":"فیلتر دیگری امتحان کن یا چیز جدیدی بساز."},

    # ---- Settings ----
    "Account": {"tr":"Hesap","de":"Konto","es":"Cuenta","fr":"Compte","it":"Account","pt":"Conta","nl":"Account","ru":"Аккаунт","ja":"アカウント","ko":"계정","zh-Hans":"账户","ar":"الحساب","cs":"Účet","fi":"Tili","hr":"Račun","fa":"حساب"},
    "Premium": {"tr":"Premium","de":"Premium","es":"Premium","fr":"Premium","it":"Premium","pt":"Premium","nl":"Premium","ru":"Премиум","ja":"プレミアム","ko":"프리미엄","zh-Hans":"高级版","ar":"بريميوم","cs":"Premium","fi":"Premium","hr":"Premium","fa":"پریمیوم"},
    "Active": {"tr":"Aktif","de":"Aktiv","es":"Activo","fr":"Actif","it":"Attivo","pt":"Ativo","nl":"Actief","ru":"Активен","ja":"有効","ko":"사용 중","zh-Hans":"已激活","ar":"مفعّل","cs":"Aktivní","fi":"Aktiivinen","hr":"Aktivno","fa":"فعال"},
    "Free": {"tr":"Ücretsiz","de":"Kostenlos","es":"Gratis","fr":"Gratuit","it":"Gratis","pt":"Grátis","nl":"Gratis","ru":"Бесплатно","ja":"無料","ko":"무료","zh-Hans":"免费","ar":"مجاني","cs":"Zdarma","fi":"Ilmainen","hr":"Besplatno","fa":"رایگان"},
    "Recipes created": {"tr":"Oluşturulan tarifler","de":"Erstellte Rezepte","es":"Recetas creadas","fr":"Recettes créées","it":"Ricette create","pt":"Receitas criadas","nl":"Gemaakte recepten","ru":"Создано рецептов","ja":"作成したレシピ","ko":"만든 레시피","zh-Hans":"已创建食谱","ar":"الوصفات المنشأة","cs":"Vytvořené recepty","fi":"Luodut reseptit","hr":"Stvoreni recepti","fa":"دستورهای ساخته‌شده"},
    "Language": {"tr":"Dil","de":"Sprache","es":"Idioma","fr":"Langue","it":"Lingua","pt":"Idioma","nl":"Taal","ru":"Язык","ja":"言語","ko":"언어","zh-Hans":"语言","ar":"اللغة","cs":"Jazyk","fi":"Kieli","hr":"Jezik","fa":"زبان"},
    "Appearance": {"tr":"Görünüm","de":"Erscheinungsbild","es":"Apariencia","fr":"Apparence","it":"Aspetto","pt":"Aparência","nl":"Weergave","ru":"Оформление","ja":"外観","ko":"화면 모드","zh-Hans":"外观","ar":"المظهر","cs":"Vzhled","fi":"Ulkoasu","hr":"Izgled","fa":"ظاهر"},
    "Send feedback": {"tr":"Geri bildirim gönder","de":"Feedback senden","es":"Enviar comentarios","fr":"Envoyer un retour","it":"Invia feedback","pt":"Enviar feedback","nl":"Feedback sturen","ru":"Отправить отзыв","ja":"フィードバックを送る","ko":"피드백 보내기","zh-Hans":"发送反馈","ar":"إرسال ملاحظات","cs":"Odeslat zpětnou vazbu","fi":"Lähetä palautetta","hr":"Pošalji povratnu informaciju","fa":"ارسال بازخورد"},
    "Rate WhichFood": {"tr":"WhichFood'u değerlendir","de":"WhichFood bewerten","es":"Valorar WhichFood","fr":"Noter WhichFood","it":"Valuta WhichFood","pt":"Avaliar o WhichFood","nl":"WhichFood beoordelen","ru":"Оценить WhichFood","ja":"WhichFoodを評価","ko":"WhichFood 평가하기","zh-Hans":"评价 WhichFood","ar":"قيّم WhichFood","cs":"Ohodnotit WhichFood","fi":"Arvioi WhichFood","hr":"Ocijeni WhichFood","fa":"امتیاز به WhichFood"},
    "Share the app": {"tr":"Uygulamayı paylaş","de":"App teilen","es":"Compartir la app","fr":"Partager l'app","it":"Condividi l'app","pt":"Partilhar a app","nl":"App delen","ru":"Поделиться приложением","ja":"アプリを共有","ko":"앱 공유하기","zh-Hans":"分享应用","ar":"مشاركة التطبيق","cs":"Sdílet aplikaci","fi":"Jaa sovellus","hr":"Podijeli aplikaciju","fa":"اشتراک‌گذاری برنامه"},
    "Go Premium": {"tr":"Premium'a geç","de":"Premium holen","es":"Hazte Premium","fr":"Passer Premium","it":"Passa a Premium","pt":"Obter Premium","nl":"Word Premium","ru":"Оформить Премиум","ja":"プレミアムにする","ko":"프리미엄 가입","zh-Hans":"升级高级版","ar":"احصل على بريميوم","cs":"Získat Premium","fi":"Hanki Premium","hr":"Postani Premium","fa":"دریافت پریمیوم"},
    "Premium plan · Unlimited AI recipes": {"tr":"Premium plan · Sınırsız AI tarif","de":"Premium-Plan · Unbegrenzte KI-Rezepte","es":"Plan Premium · Recetas con IA ilimitadas","fr":"Offre Premium · Recettes IA illimitées","it":"Piano Premium · Ricette IA illimitate","pt":"Plano Premium · Receitas IA ilimitadas","nl":"Premium-abonnement · Onbeperkt AI-recepten","ru":"Премиум · Безлимитные AI-рецепты","ja":"プレミアムプラン · AIレシピ無制限","ko":"프리미엄 플랜 · 무제한 AI 레시피","zh-Hans":"高级版 · 无限 AI 食谱","ar":"خطة بريميوم · وصفات ذكاء اصطناعي بلا حدود","cs":"Premium · Neomezené AI recepty","fi":"Premium · Rajattomat tekoälyreseptit","hr":"Premium plan · Neograničeni AI recepti","fa":"طرح پریمیوم · دستورهای هوش مصنوعی نامحدود"},
    "Free plan · %d AI recipes left": {"tr":"Ücretsiz plan · %d AI tarif kaldı","de":"Gratis-Plan · %d KI-Rezepte übrig","es":"Plan gratis · %d recetas con IA restantes","fr":"Offre gratuite · %d recettes IA restantes","it":"Piano gratis · %d ricette IA rimaste","pt":"Plano grátis · %d receitas IA restantes","nl":"Gratis abonnement · %d AI-recepten over","ru":"Бесплатно · осталось %d AI-рецептов","ja":"無料プラン · 残り%d件のAIレシピ","ko":"무료 플랜 · AI 레시피 %d개 남음","zh-Hans":"免费版 · 剩余 %d 个 AI 食谱","ar":"الخطة المجانية · بقي %d وصفة ذكاء اصطناعي","cs":"Zdarma · zbývá %d AI receptů","fi":"Ilmainen · %d tekoälyreseptiä jäljellä","hr":"Besplatni plan · preostalo %d AI recepata","fa":"طرح رایگان · %d دستور هوش مصنوعی باقی مانده"},
    "Debug: Premium": {"tr":"Hata ayıklama: Premium","de":"Debug: Premium","es":"Debug: Premium","fr":"Debug : Premium","it":"Debug: Premium","pt":"Debug: Premium","nl":"Debug: Premium","ru":"Отладка: Премиум","ja":"デバッグ：プレミアム","ko":"디버그: 프리미엄","zh-Hans":"调试：高级版","ar":"تصحيح: بريميوم","cs":"Ladění: Premium","fi":"Debug: Premium","hr":"Debug: Premium","fa":"دیباگ: پریمیوم"},
    "Bypass the AI generation limit": {"tr":"AI oluşturma limitini atla","de":"KI-Generierungslimit umgehen","es":"Omitir el límite de generación con IA","fr":"Contourner la limite de génération IA","it":"Ignora il limite di generazione IA","pt":"Ignorar o limite de geração IA","nl":"AI-generatielimiet omzeilen","ru":"Обойти лимит AI-генераций","ja":"AI生成の上限を回避","ko":"AI 생성 제한 우회","zh-Hans":"绕过 AI 生成限制","ar":"تجاوز حد إنشاء الذكاء الاصطناعي","cs":"Obejít limit AI generování","fi":"Ohita tekoälyn luontiraja","hr":"Zaobiđi ograničenje AI generiranja","fa":"دور زدن محدودیت تولید هوش مصنوعی"},
    "Terms": {"tr":"Koşullar","de":"AGB","es":"Términos","fr":"Conditions","it":"Termini","pt":"Termos","nl":"Voorwaarden","ru":"Условия","ja":"利用規約","ko":"약관","zh-Hans":"条款","ar":"الشروط","cs":"Podmínky","fi":"Ehdot","hr":"Uvjeti","fa":"شرایط"},
    "Privacy": {"tr":"Gizlilik","de":"Datenschutz","es":"Privacidad","fr":"Confidentialité","it":"Privacy","pt":"Privacidade","nl":"Privacy","ru":"Конфиденциальность","ja":"プライバシー","ko":"개인정보","zh-Hans":"隐私","ar":"الخصوصية","cs":"Soukromí","fi":"Yksityisyys","hr":"Privatnost","fa":"حریم خصوصی"},

    # ---- Preference / mood options (display only; value stays English) ----
    "Medium": {"tr":"Orta","de":"Mittel","es":"Media","fr":"Moyen","it":"Media","pt":"Média","nl":"Gemiddeld","ru":"Средне","ja":"普通","ko":"보통","zh-Hans":"中等","ar":"متوسط","cs":"Střední","fi":"Keskitaso","hr":"Srednje","fa":"متوسط"},
    "Difficult": {"tr":"Zor","de":"Schwer","es":"Difícil","fr":"Difficile","it":"Difficile","pt":"Difícil","nl":"Moeilijk","ru":"Сложно","ja":"難しい","ko":"어려움","zh-Hans":"困难","ar":"صعب","cs":"Obtížné","fi":"Vaikea","hr":"Teško","fa":"سخت"},
    "Healthy": {"tr":"Sağlıklı","de":"Gesund","es":"Saludable","fr":"Sain","it":"Sano","pt":"Saudável","nl":"Gezond","ru":"Полезное","ja":"ヘルシー","ko":"건강식","zh-Hans":"健康","ar":"صحي","cs":"Zdravé","fi":"Terveellinen","hr":"Zdravo","fa":"سالم"},
    "Vegan": {"tr":"Vegan","de":"Vegan","es":"Vegano","fr":"Végan","it":"Vegano","pt":"Vegano","nl":"Veganistisch","ru":"Веганское","ja":"ヴィーガン","ko":"비건","zh-Hans":"纯素","ar":"نباتي صرف","cs":"Veganské","fi":"Vegaaninen","hr":"Vegansko","fa":"وگان"},
    "Breakfast": {"tr":"Kahvaltı","de":"Frühstück","es":"Desayuno","fr":"Petit-déjeuner","it":"Colazione","pt":"Pequeno-almoço","nl":"Ontbijt","ru":"Завтрак","ja":"朝食","ko":"아침","zh-Hans":"早餐","ar":"فطور","cs":"Snídaně","fi":"Aamiainen","hr":"Doručak","fa":"صبحانه"},
    "Lunch": {"tr":"Öğle yemeği","de":"Mittagessen","es":"Almuerzo","fr":"Déjeuner","it":"Pranzo","pt":"Almoço","nl":"Lunch","ru":"Обед","ja":"昼食","ko":"점심","zh-Hans":"午餐","ar":"غداء","cs":"Oběd","fi":"Lounas","hr":"Ručak","fa":"ناهار"},
    "Dinner": {"tr":"Akşam yemeği","de":"Abendessen","es":"Cena","fr":"Dîner","it":"Cena","pt":"Jantar","nl":"Diner","ru":"Ужин","ja":"夕食","ko":"저녁","zh-Hans":"晚餐","ar":"عشاء","cs":"Večeře","fi":"Illallinen","hr":"Večera","fa":"شام"},
    "Hearty": {"tr":"Doyurucu","de":"Herzhaft","es":"Contundente","fr":"Copieux","it":"Sostanzioso","pt":"Substancial","nl":"Stevig","ru":"Сытное","ja":"ボリューム","ko":"든든한","zh-Hans":"丰盛","ar":"مشبع","cs":"Vydatné","fi":"Täyttävä","hr":"Zasitno","fa":"سیرکننده"},

    # ---- Creation flow (ingredient selection) ----
    "Couldn't create a recipe": {"tr":"Tarif oluşturulamadı","de":"Rezept konnte nicht erstellt werden","es":"No se pudo crear la receta","fr":"Impossible de créer la recette","it":"Impossibile creare la ricetta","pt":"Não foi possível criar a receita","nl":"Recept kon niet worden gemaakt","ru":"Не удалось создать рецепт","ja":"レシピを作成できませんでした","ko":"레시피를 만들 수 없습니다","zh-Hans":"无法创建食谱","ar":"تعذّر إنشاء الوصفة","cs":"Recept se nepodařilo vytvořit","fi":"Reseptin luonti epäonnistui","hr":"Recept nije moguće stvoriti","fa":"ساخت دستور ممکن نشد"},
    "Try again": {"tr":"Tekrar dene","de":"Erneut versuchen","es":"Reintentar","fr":"Réessayer","it":"Riprova","pt":"Tentar de novo","nl":"Opnieuw proberen","ru":"Повторить","ja":"再試行","ko":"다시 시도","zh-Hans":"重试","ar":"حاول مجددًا","cs":"Zkusit znovu","fi":"Yritä uudelleen","hr":"Pokušaj ponovno","fa":"دوباره تلاش کن"},
    "Close": {"tr":"Kapat","de":"Schließen","es":"Cerrar","fr":"Fermer","it":"Chiudi","pt":"Fechar","nl":"Sluiten","ru":"Закрыть","ja":"閉じる","ko":"닫기","zh-Hans":"关闭","ar":"إغلاق","cs":"Zavřít","fi":"Sulje","hr":"Zatvori","fa":"بستن"},
    "What are you in the mood for?": {"tr":"Canın ne istiyor?","de":"Worauf hast du Lust?","es":"¿Qué te apetece?","fr":"De quoi as-tu envie ?","it":"Cosa ti va?","pt":"Do que tens vontade?","nl":"Waar heb je zin in?","ru":"Чего вам хочется?","ja":"どんな気分ですか？","ko":"어떤 게 당기나요?","zh-Hans":"你想吃点什么？","ar":"ماذا تشتهي؟","cs":"Na co máte chuť?","fi":"Mitä tekisi mieli?","hr":"Što ti se jede?","fa":"دلت چی می‌خواد؟"},
    "Pick as many as you like — we'll shape the recipe around them.": {"tr":"İstediğin kadar seç — tarifi ona göre şekillendiririz.","de":"Wähle so viele du magst – wir gestalten das Rezept darum.","es":"Elige los que quieras: crearemos la receta a partir de ellos.","fr":"Choisis-en autant que tu veux — nous façonnerons la recette autour.","it":"Scegline quanti vuoi — creeremo la ricetta attorno a essi.","pt":"Escolhe os que quiseres — criamos a receita à volta deles.","nl":"Kies er zoveel je wilt — we bouwen het recept eromheen.","ru":"Выберите сколько угодно — составим рецепт из них.","ja":"好きなだけ選んでください。それを元にレシピを作ります。","ko":"원하는 만큼 고르세요. 그에 맞춰 레시피를 만들어요.","zh-Hans":"想选多少就选多少，我们会据此定制食谱。","ar":"اختر ما تشاء — سنبني الوصفة حولها.","cs":"Vyberte, kolik chcete — recept vytvoříme podle nich.","fi":"Valitse niin monta kuin haluat — muotoilemme reseptin niiden ympärille.","hr":"Odaberi koliko želiš — recept ćemo oblikovati oko njih.","fa":"هرچقدر می‌خواهی انتخاب کن — دستور را بر اساسشان می‌سازیم."},
    "Choose ingredients": {"tr":"Malzemeleri seç","de":"Zutaten wählen","es":"Elegir ingredientes","fr":"Choisir des ingrédients","it":"Scegli ingredienti","pt":"Escolher ingredientes","nl":"Ingrediënten kiezen","ru":"Выбрать ингредиенты","ja":"材料を選ぶ","ko":"재료 선택","zh-Hans":"选择食材","ar":"اختيار المكوّنات","cs":"Vybrat suroviny","fi":"Valitse ainekset","hr":"Odaberi sastojke","fa":"انتخاب مواد اولیه"},
    "No ingredients match that search.": {"tr":"Bu aramaya uyan malzeme yok.","de":"Keine Zutaten passen zu dieser Suche.","es":"Ningún ingrediente coincide con esa búsqueda.","fr":"Aucun ingrédient ne correspond à cette recherche.","it":"Nessun ingrediente corrisponde alla ricerca.","pt":"Nenhum ingrediente corresponde a essa pesquisa.","nl":"Geen ingrediënten komen overeen met die zoekopdracht.","ru":"Нет ингредиентов по этому запросу.","ja":"検索に一致する材料がありません。","ko":"검색과 일치하는 재료가 없어요.","zh-Hans":"没有匹配该搜索的食材。","ar":"لا توجد مكوّنات تطابق البحث.","cs":"Hledání neodpovídají žádné suroviny.","fi":"Hakua vastaavia aineksia ei löytynyt.","hr":"Nema sastojaka koji odgovaraju pretrazi.","fa":"هیچ ماده‌ای با این جستجو مطابقت ندارد."},
    "What's in your kitchen?": {"tr":"Mutfağında neler var?","de":"Was hast du in der Küche?","es":"¿Qué tienes en la cocina?","fr":"Qu'y a-t-il dans ta cuisine ?","it":"Cosa hai in cucina?","pt":"O que tens na cozinha?","nl":"Wat heb je in je keuken?","ru":"Что у вас на кухне?","ja":"キッチンには何がありますか？","ko":"주방에 뭐가 있나요?","zh-Hans":"你的厨房里有什么？","ar":"ماذا لديك في مطبخك؟","cs":"Co máte v kuchyni?","fi":"Mitä keittiöstäsi löytyy?","hr":"Što imaš u kuhinji?","fa":"در آشپزخانه‌ات چه داری؟"},
    "Search ingredients": {"tr":"Malzeme ara","de":"Zutaten suchen","es":"Buscar ingredientes","fr":"Rechercher des ingrédients","it":"Cerca ingredienti","pt":"Procurar ingredientes","nl":"Ingrediënten zoeken","ru":"Поиск ингредиентов","ja":"材料を検索","ko":"재료 검색","zh-Hans":"搜索食材","ar":"ابحث عن مكوّنات","cs":"Hledat suroviny","fi":"Hae aineksia","hr":"Pretraži sastojke","fa":"جستجوی مواد اولیه"},
    "Your ingredients": {"tr":"Malzemelerin","de":"Deine Zutaten","es":"Tus ingredientes","fr":"Tes ingrédients","it":"I tuoi ingredienti","pt":"Os teus ingredientes","nl":"Jouw ingrediënten","ru":"Ваши ингредиенты","ja":"あなたの材料","ko":"내 재료","zh-Hans":"你的食材","ar":"مكوّناتك","cs":"Vaše suroviny","fi":"Aineksesi","hr":"Vaši sastojci","fa":"مواد اولیه شما"},
    "Tap one to remove it.": {"tr":"Kaldırmak için birine dokun.","de":"Zum Entfernen antippen.","es":"Toca uno para quitarlo.","fr":"Touche pour en retirer un.","it":"Tocca per rimuoverlo.","pt":"Toca num para o remover.","nl":"Tik erop om te verwijderen.","ru":"Нажмите, чтобы удалить.","ja":"タップして削除します。","ko":"탭하면 제거돼요.","zh-Hans":"点按即可移除。","ar":"اضغط لإزالته.","cs":"Klepnutím odeberete.","fi":"Napauta poistaaksesi.","hr":"Dodirni za uklanjanje.","fa":"برای حذف روی آن بزن."},
    "Generate recipe": {"tr":"Tarif oluştur","de":"Rezept generieren","es":"Generar receta","fr":"Générer la recette","it":"Genera ricetta","pt":"Gerar receita","nl":"Recept genereren","ru":"Создать рецепт","ja":"レシピを生成","ko":"레시피 생성","zh-Hans":"生成食谱","ar":"إنشاء الوصفة","cs":"Vytvořit recept","fi":"Luo resepti","hr":"Generiraj recept","fa":"ساخت دستور"},
    "Generate": {"tr":"Oluştur","de":"Generieren","es":"Generar","fr":"Générer","it":"Genera","pt":"Gerar","nl":"Genereren","ru":"Создать","ja":"生成","ko":"생성","zh-Hans":"生成","ar":"إنشاء","cs":"Vytvořit","fi":"Luo","hr":"Generiraj","fa":"ساختن"},
    "Ready to turn them into a recipe": {"tr":"Tarife dönüştürmeye hazır","de":"Bereit, daraus ein Rezept zu machen","es":"Listos para convertirse en receta","fr":"Prêts à devenir une recette","it":"Pronti a diventare una ricetta","pt":"Prontos para virar receita","nl":"Klaar om er een recept van te maken","ru":"Готовы превратиться в рецепт","ja":"レシピにする準備ができました","ko":"레시피로 만들 준비 완료","zh-Hans":"准备好变成食谱了","ar":"جاهزة لتتحوّل إلى وصفة","cs":"Připraveno stát se receptem","fi":"Valmiina reseptiksi","hr":"Spremno za pretvaranje u recept","fa":"آماده تبدیل به دستور"},
    "Review": {"tr":"Gözden geçir","de":"Überblick","es":"Revisar","fr":"Récapitulatif","it":"Riepilogo","pt":"Rever","nl":"Overzicht","ru":"Обзор","ja":"確認","ko":"검토","zh-Hans":"确认","ar":"مراجعة","cs":"Přehled","fi":"Tarkista","hr":"Pregled","fa":"بازبینی"},
    "%d ingredients selected": {"tr":"%d malzeme seçildi","de":"%d Zutaten ausgewählt","es":"%d ingredientes seleccionados","fr":"%d ingrédients sélectionnés","it":"%d ingredienti selezionati","pt":"%d ingredientes selecionados","nl":"%d ingrediënten geselecteerd","ru":"Выбрано ингредиентов: %d","ja":"%d個の材料を選択","ko":"재료 %d개 선택됨","zh-Hans":"已选择 %d 种食材","ar":"تم اختيار %d مكوّن","cs":"Vybráno %d surovin","fi":"%d ainesta valittu","hr":"Odabrano %d sastojaka","fa":"%d ماده انتخاب شد"},
}


def parse_keys(path):
    keys = set()
    with open(path, encoding="utf-8") as f:
        for line in f:
            s = line.strip()
            if s.startswith('"') and '" = "' in s:
                keys.add(s.split('" = "', 1)[0][1:])
    return keys


def escape(v):
    return v.replace('"', '\\"')


def main():
    langs = sorted(d for d in os.listdir(LDIR) if d.endswith(".lproj"))
    for lproj in langs:
        code = lproj[:-6]
        tkey = BASE.get(code, code)
        path = os.path.join(LDIR, lproj, "Localizable.strings")
        if not os.path.exists(path):
            continue
        existing = parse_keys(path)
        additions = []
        for eng, table in T.items():
            if eng in existing:
                continue
            if code == "en" or tkey == "en":
                val = eng
            else:
                val = table.get(tkey) or table.get(code) or eng
            additions.append(f'"{escape(eng)}" = "{escape(val)}";')
        if not additions:
            print(f"{lproj}: nothing to add")
            continue
        with open(path, "a", encoding="utf-8") as f:
            f.write("\n\n// Redesign UI (auto-added)\n")
            f.write("\n".join(additions))
            f.write("\n")
        print(f"{lproj}: added {len(additions)} keys")


if __name__ == "__main__":
    main()
